import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import NavigationBar from "./navigationbar";
import { Box, CssBaseline } from "@mui/material";
import Footer from "./footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import React from 'react';

export default function RootLayout({ children }) {
  return (

    <Box lang="en" component='html' sx={{
      display: 'flex',
      flexDirection: 'column',
      minHeight: '100%'
    }}
    >
      <AppRouterCacheProvider>
        <body>
          <NavigationBar />
            {children}
          <Footer />
        </body>
      </AppRouterCacheProvider>
    </Box>


  );
}
